FROM %s:%s

RUN pip3 install debugpy

# Copy the dependencies from the active venv
COPY %s ${LAMBDA_TASK_ROOT}
# Copy source code
COPY src/* ${LAMBDA_TASK_ROOT}

# Override the bootstrap script to allow for debugging
COPY bootstrap.sh /var/runtime/bootstrap

CMD [ "%s" ]