name: CI/CD

on:
  push:
    branches:
      - '**'

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        run: go vet ./...
      - name: Test
        run: go test ./...
      - name: Build
        run: go build

